const assert = require("node:assert/strict");
const { listStateRecordFromComponents, memoryWordsFromComponents, twoHalvesFromComponents } = require("./state_fixture.js");
const { execFileSync } = require("node:child_process");
const path = require("node:path");
const test = require("node:test");
const { initialize } = require("../dist/src/pascal/initialize.js");

function runProbeText(name, args) {
  const probePath = path.resolve(process.cwd(), "scripts/probe_math");
  return execFileSync(
    probePath,
    [name, ...args.map((arg) => String(arg))],
    { encoding: "utf8" },
  ).replace(/\r?\n$/, "");
}

test("initialize matches Pascal probe trace", () => {
  const state = {
    dviBufSize: 1024,
    trieOpSize: 8,
    fontMax: 8,
    xchr: new Array(256).fill("?"),
    xord: new Array(256).fill(-1),
    interaction: 0,
    deletionsAllowed: false,
    setBoxAllowed: false,
    errorCount: 99,
    helpPtr: 9,
    useErrHelp: true,
    interrupt: 7,
    okToInterrupt: false,
    nestPtr: 9,
    maxNestStack: 9,
    shownMode: 0,
    pageContents: 0,
    pageTail: 0,
    lastGlue: 0,
    lastPenalty: 0,
    lastKern: 0,
    lastNodeType: 0,
    pageSoFar: new Array(10).fill(0),
    pageMaxDepth: 0,
    xeqLevel: new Array(7000).fill(0),
    noNewControlSequence: false,
    savePtr: 0,
    curLevel: 0,
    curGroup: 0,
    curBoundary: 0,
    maxSaveStack: 0,
    magSet: 0,
    curMark: new Array(10).fill(0),
    curVal: 0,
    curValLevel: 0,
    radix: 0,
    curOrder: 0,
    readOpen: new Array(20).fill(0),
    condPtr: 0,
    ifLimit: 0,
    curIf: 0,
    ifLine: 0,
    texFormatDefault: "",
    fontUsed: new Array(16).fill(true),
    nullCharacter: { b0: 0, b1: 0, b2: 0, b3: 0 },
    totalPages: 0,
    maxV: 0,
    maxH: 0,
    maxPush: 0,
    lastBop: 0,
    doingLeaders: false,
    deadCycles: 0,
    curS: 0,
    halfBuf: 0,
    dviLimit: 0,
    dviPtr: 0,
    dviOffset: 0,
    dviGone: 0,
    downPtr: 0,
    rightPtr: 0,
    adjustTail: 0,
    lastBadness: 0,
    packBeginLine: 0,
    emptyField: { lh: 0, rh: 0, b0: 0, b1: 0 },
    nullDelimiter: { b0: 0, b1: 0, b2: 0, b3: 0 },
    alignPtr: 0,
    curAlign: 0,
    curSpan: 0,
    curLoop: 0,
    curHead: 0,
    curTail: 0,
    hyphWord: new Array(400).fill(1),
    hyphList: new Array(400).fill(1),
    hyphCount: 0,
    outputActive: true,
    insertPenalties: 5,
    ligaturePresent: true,
    cancelBoundary: true,
    lftHit: true,
    rtHit: true,
    insDisc: true,
    afterToken: 999,
    longHelpSeen: true,
    formatIdent: 999,
    writeOpen: new Array(18).fill(true),
    lrPtr: 0,
    lrProblems: 0,
    curDir: 0,
    pseudoFiles: 0,
    saRoot: new Array(8).fill(0),
    saNull: {
      int: 0,
      gr: 0,
      hh: { b0: 0, b1: 0, lh: 0, rh: 0 },
      qqqq: { b0: 0, b1: 0, b2: 0, b3: 0 },
    },
    saChain: 0,
    saLevel: 0,
    discPtr: new Array(10).fill(0),
    rover: 0,
    loMemMax: 0,
    avail: 0,
    memEnd: 0,
    hiMemMin: 0,
    varUsed: 0,
    dynUsed: 0,
    hashUsed: 0,
    csCount: 0,
    fontPtr: 0,
    fmemPtr: 0,
    fontName: new Array(16).fill(0),
    fontArea: new Array(16).fill(0),
    hyphenChar: new Array(16).fill(0),
    skewChar: new Array(16).fill(0),
    bcharLabel: new Array(16).fill(0),
    fontBchar: new Array(16).fill(0),
    fontFalseBchar: new Array(16).fill(0),
    fontBc: new Array(16).fill(0),
    fontEc: new Array(16).fill(0),
    fontSize: new Array(16).fill(0),
    fontDsize: new Array(16).fill(0),
    charBase: new Array(16).fill(0),
    widthBase: new Array(16).fill(0),
    heightBase: new Array(16).fill(0),
    depthBase: new Array(16).fill(0),
    italicBase: new Array(16).fill(0),
    ligKernBase: new Array(16).fill(0),
    kernBase: new Array(16).fill(0),
    extenBase: new Array(16).fill(0),
    fontGlue: new Array(16).fill(0),
    fontParams: new Array(16).fill(0),
    paramBase: new Array(16).fill(0),
    trieOpHash: {},
    trieUsed: new Array(300).fill(0),
    trieOpPtr: 0,
    trieNotReady: false,
    trieL: new Array(128).fill(0),
    trieC: new Array(128).fill(0),
    triePtr: 0,
    eTeXMode: 0,
    maxRegNum: 0,
    maxRegHelpLine: 0,
    trieR: new Array(128).fill(0),
    hyphStart: 0,
    mem: memoryWordsFromComponents({
      b0: new Array(70000).fill(0),
      b1: new Array(70000).fill(0),
      int: new Array(70000).fill(0),
      lh: new Array(70000).fill(0),
      rh: new Array(70000).fill(0),
      }, { minSize: 30001 }),
    eqtb: memoryWordsFromComponents({
      b0: new Array(7000).fill(0),
      b1: new Array(7000).fill(0),
      int: new Array(7000).fill(0),
      rh: new Array(7000).fill(0),
      }),
    fontInfo: memoryWordsFromComponents({
      int: new Array(64).fill(0),
      }),
    hash: twoHalvesFromComponents({
      lh: new Array(7000).fill(1),
      rh: new Array(7000).fill(1),
      }),
    curList: listStateRecordFromComponents({
      modeField: 0,
      headField: 0,
      tailField: 0,
      eTeXAuxField: 0,
      pgField: 0,
      mlField: 0,
      auxInt: 0,
      }),
  };

  initialize(state);

  const actual = `M${state.xchr[32].charCodeAt(0)},${state.xchr[65].charCodeAt(0)},${state.xchr[127].charCodeAt(0)},${state.xord[32]},${state.xord[65]},${state.xord[0]},${state.interaction},${state.deletionsAllowed ? 1 : 0},${state.setBoxAllowed ? 1 : 0},${state.errorCount},${state.helpPtr},${state.useErrHelp ? 1 : 0},${state.interrupt},${state.okToInterrupt ? 1 : 0},${state.nestPtr},${state.curList.modeField},${state.curList.headField},${state.curList.tailField},${state.curList.auxField.int},${state.pageContents},${state.pageTail},${state.mem[29998].hh.rh},${state.lastGlue},${state.lastPenalty},${state.lastKern},${state.lastNodeType},${state.pageSoFar[7]},${state.pageMaxDepth},${state.xeqLevel[5268]},${state.xeqLevel[6121]},${state.hash[514].lh},${state.hash[514].rh},${state.hash[515].lh},${state.hash[515].rh},${state.savePtr},${state.curLevel},${state.curGroup},${state.curBoundary},${state.magSet},${state.curMark[0]},${state.curMark[4]},${state.readOpen[0]},${state.readOpen[16]},${state.condPtr},${state.ifLimit},${state.curIf},${state.ifLine},${state.nullCharacter.b0},${state.nullCharacter.b1},${state.nullCharacter.b2},${state.nullCharacter.b3},${state.deadCycles},${state.curS},${state.halfBuf},${state.dviLimit},${state.dviPtr},${state.dviOffset},${state.dviGone},${state.emptyField.lh},${state.emptyField.rh},${state.alignPtr},${state.hyphWord[0]},${state.hyphWord[307]},${state.hyphCount},${state.outputActive ? 1 : 0},${state.insertPenalties},${state.afterToken},${state.longHelpSeen ? 1 : 0},${state.formatIdent},${state.writeOpen[0] ? 1 : 0},${state.writeOpen[17] ? 1 : 0},${state.saRoot[0]},${state.saRoot[6]},${state.discPtr[2]},${state.discPtr[3]},${state.mem[4].hh.b0},${state.mem[6].int},${state.mem[8].hh.b0},${state.mem[10].int},${state.mem[12].hh.b0},${state.mem[12].hh.b1},${state.mem[14].int},${state.mem[15].int},${state.mem[16].hh.b0},${state.mem[18].int},${state.rover},${state.mem[20].hh.rh},${state.mem[20].hh.lh},${state.mem[21].hh.lh},${state.mem[21].hh.rh},${state.loMemMax},${state.mem[29990].hh.lh},${state.mem[29991].hh.rh},${state.mem[29991].hh.lh},${state.mem[29993].hh.b0},${state.mem[29994].hh.lh},${state.mem[30000].hh.b1},${state.mem[30000].hh.rh},${state.mem[29998].hh.b0},${state.mem[29998].hh.b1},${state.avail},${state.memEnd},${state.hiMemMin},${state.varUsed},${state.dynUsed},${state.eqtb[2881].hh.b0},${state.eqtb[2882].hh.b0},${state.eqtb[2882].hh.b1},${state.eqtb[3412].hh.b0},${state.eqtb[3683].hh.b0},${state.eqtb[3939].hh.b0},${state.eqtb[3988].hh.b0},${state.eqtb[3988].hh.rh},${state.eqtb[4001].hh.rh},${state.eqtb[4020].hh.rh},${state.eqtb[4025].hh.rh},${state.eqtb[4080].hh.rh},${state.eqtb[4115].hh.rh},${state.eqtb[5012 + 48].hh.rh},${state.eqtb[5012 + 65].hh.rh},${state.eqtb[5012 + 97].hh.rh},${state.eqtb[4244 + 65].hh.rh},${state.eqtb[4500 + 97].hh.rh},${state.eqtb[4756 + 65].hh.rh},${state.eqtb[5269].int},${state.eqtb[5285].int},${state.eqtb[5308].int},${state.eqtb[5309].int},${state.eqtb[5313].int},${state.eqtb[5316].int},${state.eqtb[5589].int},${state.eqtb[5635].int},${state.eqtb[5845].int},${state.eqtb[6121].int},${state.hashUsed},${state.csCount},${state.hash[2614].rh},${state.hash[2622].rh},${state.hash[2623].rh},${state.eqtb[2622].hh.b0},${state.eqtb[2622].hh.b1},${state.eqtb[2622].hh.rh},${state.fontPtr},${state.fmemPtr},${state.fontName[0]},${state.fontArea[0]},${state.hyphenChar[0]},${state.skewChar[0]},${state.fontBchar[0]},${state.fontFalseBchar[0]},${state.fontBc[0]},${state.fontEc[0]},${state.fontParams[0]},${state.paramBase[0]},${state.trieOpHash[-8]},${state.trieOpHash[0]},${state.trieOpHash[8]},${state.trieUsed[0]},${state.trieUsed[255]},${state.trieOpPtr},${state.trieNotReady ? 1 : 0},${state.trieL[0]},${state.trieC[0]},${state.triePtr},${state.eTeXMode},${state.maxRegNum},${state.maxRegHelpLine},${state.trieR[0]},${state.hyphStart},${state.texFormatDefault}`;

  const expected = runProbeText("INITIALIZE_TRACE", [1]);
  assert.equal(actual, expected);
});
