const assert = require("node:assert/strict");
const { execFileSync } = require("node:child_process");
const path = require("node:path");
const test = require("node:test");
const { initialize } = require("../dist/src/pascal/initialize.js");

function runProbeText(name, args) {
  const probePath = path.resolve(process.cwd(), "scripts/probe_math");
  return execFileSync(
    probePath,
    [name, ...args.map((arg) => String(arg))],
    { encoding: "utf8" },
  ).replace(/\r?\n$/, "");
}

test("initialize matches Pascal probe trace", () => {
  const state = {
    dviBufSize: 1024,
    trieOpSize: 8,
    fontMax: 8,
    xchr: new Array(256).fill("?"),
    xord: new Array(256).fill(-1),
    interaction: 0,
    deletionsAllowed: false,
    setBoxAllowed: false,
    errorCount: 99,
    helpPtr: 9,
    useErrHelp: true,
    interrupt: 7,
    okToInterrupt: false,
    nestPtr: 9,
    maxNestStack: 9,
    curListModeField: 0,
    curListHeadField: 0,
    curListTailField: 0,
    curListETeXAuxField: 0,
    curListAuxInt: 0,
    curListMlField: 0,
    curListPgField: 0,
    shownMode: 0,
    pageContents: 0,
    pageTail: 0,
    lastGlue: 0,
    lastPenalty: 0,
    lastKern: 0,
    lastNodeType: 0,
    pageSoFar: new Array(10).fill(0),
    pageMaxDepth: 0,
    xeqLevel: new Array(7000).fill(0),
    noNewControlSequence: false,
    hashLh: new Array(7000).fill(1),
    hashRh: new Array(7000).fill(1),
    savePtr: 0,
    curLevel: 0,
    curGroup: 0,
    curBoundary: 0,
    maxSaveStack: 0,
    magSet: 0,
    curMark: new Array(10).fill(0),
    curVal: 0,
    curValLevel: 0,
    radix: 0,
    curOrder: 0,
    readOpen: new Array(20).fill(0),
    condPtr: 0,
    ifLimit: 0,
    curIf: 0,
    ifLine: 0,
    texFormatDefault: "",
    fontUsed: new Array(16).fill(true),
    nullCharacterB0: 0,
    nullCharacterB1: 0,
    nullCharacterB2: 0,
    nullCharacterB3: 0,
    totalPages: 0,
    maxV: 0,
    maxH: 0,
    maxPush: 0,
    lastBop: 0,
    doingLeaders: false,
    deadCycles: 0,
    curS: 0,
    halfBuf: 0,
    dviLimit: 0,
    dviPtr: 0,
    dviOffset: 0,
    dviGone: 0,
    downPtr: 0,
    rightPtr: 0,
    adjustTail: 0,
    lastBadness: 0,
    packBeginLine: 0,
    emptyFieldRh: 0,
    emptyFieldLh: 0,
    nullDelimiterB0: 0,
    nullDelimiterB1: 0,
    nullDelimiterB2: 0,
    nullDelimiterB3: 0,
    alignPtr: 0,
    curAlign: 0,
    curSpan: 0,
    curLoop: 0,
    curHead: 0,
    curTail: 0,
    hyphWord: new Array(400).fill(1),
    hyphList: new Array(400).fill(1),
    hyphCount: 0,
    outputActive: true,
    insertPenalties: 5,
    ligaturePresent: true,
    cancelBoundary: true,
    lftHit: true,
    rtHit: true,
    insDisc: true,
    afterToken: 999,
    longHelpSeen: true,
    formatIdent: 999,
    writeOpen: new Array(18).fill(true),
    lrPtr: 0,
    lrProblems: 0,
    curDir: 0,
    pseudoFiles: 0,
    saRoot: new Array(8).fill(0),
    saNullLh: 0,
    saNullRh: 0,
    saChain: 0,
    saLevel: 0,
    discPtr: new Array(10).fill(0),
    memB0: new Array(70000).fill(0),
    memB1: new Array(70000).fill(0),
    memLh: new Array(70000).fill(0),
    memRh: new Array(70000).fill(0),
    memInt: new Array(70000).fill(0),
    rover: 0,
    loMemMax: 0,
    avail: 0,
    memEnd: 0,
    hiMemMin: 0,
    varUsed: 0,
    dynUsed: 0,
    eqtbB0: new Array(7000).fill(0),
    eqtbB1: new Array(7000).fill(0),
    eqtbRh: new Array(7000).fill(0),
    eqtbInt: new Array(7000).fill(0),
    hashUsed: 0,
    csCount: 0,
    fontPtr: 0,
    fmemPtr: 0,
    fontName: new Array(16).fill(0),
    fontArea: new Array(16).fill(0),
    hyphenChar: new Array(16).fill(0),
    skewChar: new Array(16).fill(0),
    bcharLabel: new Array(16).fill(0),
    fontBchar: new Array(16).fill(0),
    fontFalseBchar: new Array(16).fill(0),
    fontBc: new Array(16).fill(0),
    fontEc: new Array(16).fill(0),
    fontSize: new Array(16).fill(0),
    fontDsize: new Array(16).fill(0),
    charBase: new Array(16).fill(0),
    widthBase: new Array(16).fill(0),
    heightBase: new Array(16).fill(0),
    depthBase: new Array(16).fill(0),
    italicBase: new Array(16).fill(0),
    ligKernBase: new Array(16).fill(0),
    kernBase: new Array(16).fill(0),
    extenBase: new Array(16).fill(0),
    fontGlue: new Array(16).fill(0),
    fontParams: new Array(16).fill(0),
    paramBase: new Array(16).fill(0),
    fontInfoInt: new Array(64).fill(0),
    trieOpHash: {},
    trieUsed: new Array(300).fill(0),
    trieOpPtr: 0,
    trieNotReady: false,
    trieL: new Array(128).fill(0),
    trieC: new Array(128).fill(0),
    triePtr: 0,
    eTeXMode: 0,
    maxRegNum: 0,
    maxRegHelpLine: 0,
    trieR: new Array(128).fill(0),
    hyphStart: 0,
  };

  initialize(state);

  const actual = `M${state.xchr[32].charCodeAt(0)},${state.xchr[65].charCodeAt(0)},${state.xchr[127].charCodeAt(0)},${state.xord[32]},${state.xord[65]},${state.xord[0]},${state.interaction},${state.deletionsAllowed ? 1 : 0},${state.setBoxAllowed ? 1 : 0},${state.errorCount},${state.helpPtr},${state.useErrHelp ? 1 : 0},${state.interrupt},${state.okToInterrupt ? 1 : 0},${state.nestPtr},${state.curListModeField},${state.curListHeadField},${state.curListTailField},${state.curListAuxInt},${state.pageContents},${state.pageTail},${state.memRh[29998]},${state.lastGlue},${state.lastPenalty},${state.lastKern},${state.lastNodeType},${state.pageSoFar[7]},${state.pageMaxDepth},${state.xeqLevel[5268]},${state.xeqLevel[6121]},${state.hashLh[514]},${state.hashRh[514]},${state.hashLh[515]},${state.hashRh[515]},${state.savePtr},${state.curLevel},${state.curGroup},${state.curBoundary},${state.magSet},${state.curMark[0]},${state.curMark[4]},${state.readOpen[0]},${state.readOpen[16]},${state.condPtr},${state.ifLimit},${state.curIf},${state.ifLine},${state.nullCharacterB0},${state.nullCharacterB1},${state.nullCharacterB2},${state.nullCharacterB3},${state.deadCycles},${state.curS},${state.halfBuf},${state.dviLimit},${state.dviPtr},${state.dviOffset},${state.dviGone},${state.emptyFieldLh},${state.emptyFieldRh},${state.alignPtr},${state.hyphWord[0]},${state.hyphWord[307]},${state.hyphCount},${state.outputActive ? 1 : 0},${state.insertPenalties},${state.afterToken},${state.longHelpSeen ? 1 : 0},${state.formatIdent},${state.writeOpen[0] ? 1 : 0},${state.writeOpen[17] ? 1 : 0},${state.saRoot[0]},${state.saRoot[6]},${state.discPtr[2]},${state.discPtr[3]},${state.memB0[4]},${state.memInt[6]},${state.memB0[8]},${state.memInt[10]},${state.memB0[12]},${state.memB1[12]},${state.memInt[14]},${state.memInt[15]},${state.memB0[16]},${state.memInt[18]},${state.rover},${state.memRh[20]},${state.memLh[20]},${state.memLh[21]},${state.memRh[21]},${state.loMemMax},${state.memLh[29990]},${state.memRh[29991]},${state.memLh[29991]},${state.memB0[29993]},${state.memLh[29994]},${state.memB1[30000]},${state.memRh[30000]},${state.memB0[29998]},${state.memB1[29998]},${state.avail},${state.memEnd},${state.hiMemMin},${state.varUsed},${state.dynUsed},${state.eqtbB0[2881]},${state.eqtbB0[2882]},${state.eqtbB1[2882]},${state.eqtbB0[3412]},${state.eqtbB0[3683]},${state.eqtbB0[3939]},${state.eqtbB0[3988]},${state.eqtbRh[3988]},${state.eqtbRh[4001]},${state.eqtbRh[4020]},${state.eqtbRh[4025]},${state.eqtbRh[4080]},${state.eqtbRh[4115]},${state.eqtbRh[5012 + 48]},${state.eqtbRh[5012 + 65]},${state.eqtbRh[5012 + 97]},${state.eqtbRh[4244 + 65]},${state.eqtbRh[4500 + 97]},${state.eqtbRh[4756 + 65]},${state.eqtbInt[5269]},${state.eqtbInt[5285]},${state.eqtbInt[5308]},${state.eqtbInt[5309]},${state.eqtbInt[5313]},${state.eqtbInt[5316]},${state.eqtbInt[5589]},${state.eqtbInt[5635]},${state.eqtbInt[5845]},${state.eqtbInt[6121]},${state.hashUsed},${state.csCount},${state.hashRh[2614]},${state.hashRh[2622]},${state.hashRh[2623]},${state.eqtbB0[2622]},${state.eqtbB1[2622]},${state.eqtbRh[2622]},${state.fontPtr},${state.fmemPtr},${state.fontName[0]},${state.fontArea[0]},${state.hyphenChar[0]},${state.skewChar[0]},${state.fontBchar[0]},${state.fontFalseBchar[0]},${state.fontBc[0]},${state.fontEc[0]},${state.fontParams[0]},${state.paramBase[0]},${state.trieOpHash[-8]},${state.trieOpHash[0]},${state.trieOpHash[8]},${state.trieUsed[0]},${state.trieUsed[255]},${state.trieOpPtr},${state.trieNotReady ? 1 : 0},${state.trieL[0]},${state.trieC[0]},${state.triePtr},${state.eTeXMode},${state.maxRegNum},${state.maxRegHelpLine},${state.trieR[0]},${state.hyphStart},${state.texFormatDefault}`;

  const expected = runProbeText("INITIALIZE_TRACE", [1]);
  assert.equal(actual, expected);
});
